// Nachbar Hilfe — Bundesland-Regeln (statische Daten, spiegelt DB-Seed)
// Quelle: Pflege_Matrix_BW_BY.xlsx (BW/BY geprueft), restliche Laender pending
import type { FederalStateRule } from './types';

/** Alle 16 Bundesland-Regeln */
const FEDERAL_STATE_RULES: FederalStateRule[] = [
  {
    state_code: 'BW',
    state_name: 'Baden-Wuerttemberg',
    is_available: true,
    research_status: 'checked_official_sources',
    last_checked: '2026-03-27',
    training_required: false,
    training_hours: null,
    min_age: 16,
    max_hourly_rate_cents: null,
    max_concurrent_clients: 2,
    relationship_exclusion_degree: 2,
    same_household_excluded: true,
    registration_authority: null,
    official_form_url: null,
    notes: 'Seit 01.01.2025: vereinfachte Einzelhelfenden-Abrechnung',
    recognition_type: 'Anerkennungsfiktion via signed confirmation + reimbursement form',
    formal_pre_registration: false,
    hourly_rate_min_cents: 1250,
    hourly_rate_max_cents: 2000,
    hourly_rate_note: 'Nicht gesetzlich festgelegt; Ministeriums-FAQ nennt 12,50-20,00 EUR/Stunde als ueblich',
    reimbursement_principle: 'cost_reimbursement_after_submission',
    direct_payment_possible: true,
    allowed_household: true,
    allowed_cleaning: true,
    allowed_shopping: true,
    allowed_escort: true,
    allowed_leisure: true,
    allowed_snow_removal: true,
    allowed_lawn_mowing: null,
    insurance_note: 'Eigene Haftpflicht empfohlen; keine pauschale gesetzliche Unfallversicherung',
    tax_note: 'Steuerfrei bis 3.000 EUR/Jahr (Uebungsleiterfreibetrag) bei Erfuellung der Voraussetzungen',
    primary_official_url: 'https://sozialministerium.baden-wuerttemberg.de/de/gesundheit-pflege/pflege/ehrenamt-und-selbsthilfe/anerkennung-einzelhelfende',
    secondary_official_url: 'https://sozialministerium.baden-wuerttemberg.de/fileadmin/redaktion/m-sm/intern/downloads/Downloads_Pflege/241210_AenderungsVO_UstA-VO.pdf',
  },
  {
    state_code: 'BY',
    state_name: 'Bayern',
    is_available: true,
    research_status: 'checked_official_sources',
    last_checked: '2026-03-27',
    training_required: true,
    training_hours: 8,
    min_age: 16,
    max_hourly_rate_cents: null,
    max_concurrent_clients: 3,
    relationship_exclusion_degree: 2,
    same_household_excluded: true,
    registration_authority: 'Regionale Fachstelle fuer Pflege- und Behinderteneinrichtungen',
    official_form_url: null,
    notes: 'Registrierung bei Fachstelle erforderlich; Registrierung = Anerkennung. Gartenarbeit und hausmeisterliche Taetigkeiten ausdruecklich ausgeschlossen.',
    recognition_type: 'Registrierung bei regionaler Fachstelle; Registrierung = Anerkennung',
    formal_pre_registration: true,
    hourly_rate_min_cents: null,
    hourly_rate_max_cents: null,
    hourly_rate_note: 'Kein fester Stundensatz; nur Aufwandsentschaedigung unterhalb des Mindestlohns',
    reimbursement_principle: 'mixed',
    direct_payment_possible: true,
    allowed_household: true,
    allowed_cleaning: true,
    allowed_shopping: true,
    allowed_escort: true,
    allowed_leisure: true,
    allowed_snow_removal: false,
    allowed_lawn_mowing: false,
    insurance_note: 'Haftpflicht- und Unfallversicherung erforderlich; ggf. Bayerische Ehrenamtsversicherung',
    tax_note: 'Ggf. steuerfrei; VV-AVSG verweist auf ehrenamtliche Steuerfreigrenzen',
    primary_official_url: 'https://www.stmgp.bayern.de/pflege/pflege-zu-hause/angebote-zur-unterstuetzung-im-alltag/',
    secondary_official_url: 'https://www.gesetze-bayern.de/Content/Document/BayAVSG-82',
  },
  {
    state_code: 'BE',
    state_name: 'Berlin',
    is_available: false,
    research_status: 'pending_research',
    last_checked: null,
    training_required: false,
    training_hours: null,
    min_age: 16,
    max_hourly_rate_cents: null,
    max_concurrent_clients: null,
    relationship_exclusion_degree: 2,
    same_household_excluded: true,
    registration_authority: null,
    official_form_url: null,
    notes: 'Regeln noch nicht geprueft — Daten folgen',
    recognition_type: null,
    formal_pre_registration: null,
    hourly_rate_min_cents: null,
    hourly_rate_max_cents: null,
    hourly_rate_note: null,
    reimbursement_principle: null,
    direct_payment_possible: null,
    allowed_household: null,
    allowed_cleaning: null,
    allowed_shopping: null,
    allowed_escort: null,
    allowed_leisure: null,
    allowed_snow_removal: null,
    allowed_lawn_mowing: null,
    insurance_note: null,
    tax_note: null,
    primary_official_url: null,
    secondary_official_url: null,
  },
  {
    state_code: 'BB',
    state_name: 'Brandenburg',
    is_available: false,
    research_status: 'pending_research',
    last_checked: null,
    training_required: false,
    training_hours: null,
    min_age: 16,
    max_hourly_rate_cents: null,
    max_concurrent_clients: null,
    relationship_exclusion_degree: 2,
    same_household_excluded: true,
    registration_authority: null,
    official_form_url: null,
    notes: 'Regeln noch nicht geprueft — Daten folgen',
    recognition_type: null,
    formal_pre_registration: null,
    hourly_rate_min_cents: null,
    hourly_rate_max_cents: null,
    hourly_rate_note: null,
    reimbursement_principle: null,
    direct_payment_possible: null,
    allowed_household: null,
    allowed_cleaning: null,
    allowed_shopping: null,
    allowed_escort: null,
    allowed_leisure: null,
    allowed_snow_removal: null,
    allowed_lawn_mowing: null,
    insurance_note: null,
    tax_note: null,
    primary_official_url: null,
    secondary_official_url: null,
  },
  {
    state_code: 'HB',
    state_name: 'Bremen',
    is_available: false,
    research_status: 'pending_research',
    last_checked: null,
    training_required: false,
    training_hours: null,
    min_age: 16,
    max_hourly_rate_cents: null,
    max_concurrent_clients: null,
    relationship_exclusion_degree: 2,
    same_household_excluded: true,
    registration_authority: null,
    official_form_url: null,
    notes: 'Regeln noch nicht geprueft — Daten folgen',
    recognition_type: null,
    formal_pre_registration: null,
    hourly_rate_min_cents: null,
    hourly_rate_max_cents: null,
    hourly_rate_note: null,
    reimbursement_principle: null,
    direct_payment_possible: null,
    allowed_household: null,
    allowed_cleaning: null,
    allowed_shopping: null,
    allowed_escort: null,
    allowed_leisure: null,
    allowed_snow_removal: null,
    allowed_lawn_mowing: null,
    insurance_note: null,
    tax_note: null,
    primary_official_url: null,
    secondary_official_url: null,
  },
  {
    state_code: 'HH',
    state_name: 'Hamburg',
    is_available: false,
    research_status: 'pending_research',
    last_checked: null,
    training_required: false,
    training_hours: null,
    min_age: 16,
    max_hourly_rate_cents: null,
    max_concurrent_clients: null,
    relationship_exclusion_degree: 2,
    same_household_excluded: true,
    registration_authority: null,
    official_form_url: null,
    notes: 'Regeln noch nicht geprueft — Daten folgen',
    recognition_type: null,
    formal_pre_registration: null,
    hourly_rate_min_cents: null,
    hourly_rate_max_cents: null,
    hourly_rate_note: null,
    reimbursement_principle: null,
    direct_payment_possible: null,
    allowed_household: null,
    allowed_cleaning: null,
    allowed_shopping: null,
    allowed_escort: null,
    allowed_leisure: null,
    allowed_snow_removal: null,
    allowed_lawn_mowing: null,
    insurance_note: null,
    tax_note: null,
    primary_official_url: null,
    secondary_official_url: null,
  },
  {
    state_code: 'HE',
    state_name: 'Hessen',
    is_available: false,
    research_status: 'pending_research',
    last_checked: null,
    training_required: false,
    training_hours: null,
    min_age: 16,
    max_hourly_rate_cents: null,
    max_concurrent_clients: null,
    relationship_exclusion_degree: 2,
    same_household_excluded: true,
    registration_authority: null,
    official_form_url: null,
    notes: 'Regeln noch nicht geprueft — Daten folgen',
    recognition_type: null,
    formal_pre_registration: null,
    hourly_rate_min_cents: null,
    hourly_rate_max_cents: null,
    hourly_rate_note: null,
    reimbursement_principle: null,
    direct_payment_possible: null,
    allowed_household: null,
    allowed_cleaning: null,
    allowed_shopping: null,
    allowed_escort: null,
    allowed_leisure: null,
    allowed_snow_removal: null,
    allowed_lawn_mowing: null,
    insurance_note: null,
    tax_note: null,
    primary_official_url: null,
    secondary_official_url: null,
  },
  {
    state_code: 'MV',
    state_name: 'Mecklenburg-Vorpommern',
    is_available: false,
    research_status: 'pending_research',
    last_checked: null,
    training_required: false,
    training_hours: null,
    min_age: 16,
    max_hourly_rate_cents: null,
    max_concurrent_clients: null,
    relationship_exclusion_degree: 2,
    same_household_excluded: true,
    registration_authority: null,
    official_form_url: null,
    notes: 'Regeln noch nicht geprueft — Daten folgen',
    recognition_type: null,
    formal_pre_registration: null,
    hourly_rate_min_cents: null,
    hourly_rate_max_cents: null,
    hourly_rate_note: null,
    reimbursement_principle: null,
    direct_payment_possible: null,
    allowed_household: null,
    allowed_cleaning: null,
    allowed_shopping: null,
    allowed_escort: null,
    allowed_leisure: null,
    allowed_snow_removal: null,
    allowed_lawn_mowing: null,
    insurance_note: null,
    tax_note: null,
    primary_official_url: null,
    secondary_official_url: null,
  },
  {
    state_code: 'NI',
    state_name: 'Niedersachsen',
    is_available: false,
    research_status: 'pending_research',
    last_checked: null,
    training_required: false,
    training_hours: null,
    min_age: 16,
    max_hourly_rate_cents: null,
    max_concurrent_clients: null,
    relationship_exclusion_degree: 2,
    same_household_excluded: true,
    registration_authority: null,
    official_form_url: null,
    notes: 'Regeln noch nicht geprueft — Daten folgen',
    recognition_type: null,
    formal_pre_registration: null,
    hourly_rate_min_cents: null,
    hourly_rate_max_cents: null,
    hourly_rate_note: null,
    reimbursement_principle: null,
    direct_payment_possible: null,
    allowed_household: null,
    allowed_cleaning: null,
    allowed_shopping: null,
    allowed_escort: null,
    allowed_leisure: null,
    allowed_snow_removal: null,
    allowed_lawn_mowing: null,
    insurance_note: null,
    tax_note: null,
    primary_official_url: null,
    secondary_official_url: null,
  },
  {
    state_code: 'NW',
    state_name: 'Nordrhein-Westfalen',
    is_available: false,
    research_status: 'pending_research',
    last_checked: null,
    training_required: true,
    training_hours: 30,
    min_age: 16,
    max_hourly_rate_cents: null,
    max_concurrent_clients: null,
    relationship_exclusion_degree: 2,
    same_household_excluded: true,
    registration_authority: null,
    official_form_url: null,
    notes: 'Pflegekurs oder 30h Schulung erforderlich. Regeln noch nicht vollstaendig geprueft.',
    recognition_type: null,
    formal_pre_registration: null,
    hourly_rate_min_cents: null,
    hourly_rate_max_cents: null,
    hourly_rate_note: null,
    reimbursement_principle: null,
    direct_payment_possible: null,
    allowed_household: null,
    allowed_cleaning: null,
    allowed_shopping: null,
    allowed_escort: null,
    allowed_leisure: null,
    allowed_snow_removal: null,
    allowed_lawn_mowing: null,
    insurance_note: null,
    tax_note: null,
    primary_official_url: null,
    secondary_official_url: null,
  },
  {
    state_code: 'RP',
    state_name: 'Rheinland-Pfalz',
    is_available: false,
    research_status: 'pending_research',
    last_checked: null,
    training_required: false,
    training_hours: null,
    min_age: 16,
    max_hourly_rate_cents: null,
    max_concurrent_clients: null,
    relationship_exclusion_degree: 2,
    same_household_excluded: true,
    registration_authority: null,
    official_form_url: null,
    notes: 'Regeln noch nicht geprueft — Daten folgen',
    recognition_type: null,
    formal_pre_registration: null,
    hourly_rate_min_cents: null,
    hourly_rate_max_cents: null,
    hourly_rate_note: null,
    reimbursement_principle: null,
    direct_payment_possible: null,
    allowed_household: null,
    allowed_cleaning: null,
    allowed_shopping: null,
    allowed_escort: null,
    allowed_leisure: null,
    allowed_snow_removal: null,
    allowed_lawn_mowing: null,
    insurance_note: null,
    tax_note: null,
    primary_official_url: null,
    secondary_official_url: null,
  },
  {
    state_code: 'SL',
    state_name: 'Saarland',
    is_available: false,
    research_status: 'pending_research',
    last_checked: null,
    training_required: false,
    training_hours: null,
    min_age: 16,
    max_hourly_rate_cents: null,
    max_concurrent_clients: null,
    relationship_exclusion_degree: 2,
    same_household_excluded: true,
    registration_authority: null,
    official_form_url: null,
    notes: 'Regeln noch nicht geprueft — Daten folgen',
    recognition_type: null,
    formal_pre_registration: null,
    hourly_rate_min_cents: null,
    hourly_rate_max_cents: null,
    hourly_rate_note: null,
    reimbursement_principle: null,
    direct_payment_possible: null,
    allowed_household: null,
    allowed_cleaning: null,
    allowed_shopping: null,
    allowed_escort: null,
    allowed_leisure: null,
    allowed_snow_removal: null,
    allowed_lawn_mowing: null,
    insurance_note: null,
    tax_note: null,
    primary_official_url: null,
    secondary_official_url: null,
  },
  {
    state_code: 'SN',
    state_name: 'Sachsen',
    is_available: false,
    research_status: 'pending_research',
    last_checked: null,
    training_required: false,
    training_hours: null,
    min_age: 16,
    max_hourly_rate_cents: null,
    max_concurrent_clients: null,
    relationship_exclusion_degree: 2,
    same_household_excluded: true,
    registration_authority: null,
    official_form_url: null,
    notes: 'Regeln noch nicht geprueft — Daten folgen',
    recognition_type: null,
    formal_pre_registration: null,
    hourly_rate_min_cents: null,
    hourly_rate_max_cents: null,
    hourly_rate_note: null,
    reimbursement_principle: null,
    direct_payment_possible: null,
    allowed_household: null,
    allowed_cleaning: null,
    allowed_shopping: null,
    allowed_escort: null,
    allowed_leisure: null,
    allowed_snow_removal: null,
    allowed_lawn_mowing: null,
    insurance_note: null,
    tax_note: null,
    primary_official_url: null,
    secondary_official_url: null,
  },
  {
    state_code: 'ST',
    state_name: 'Sachsen-Anhalt',
    is_available: false,
    research_status: 'pending_research',
    last_checked: null,
    training_required: false,
    training_hours: null,
    min_age: 16,
    max_hourly_rate_cents: null,
    max_concurrent_clients: null,
    relationship_exclusion_degree: 2,
    same_household_excluded: true,
    registration_authority: null,
    official_form_url: null,
    notes: 'Regeln noch nicht geprueft — Daten folgen',
    recognition_type: null,
    formal_pre_registration: null,
    hourly_rate_min_cents: null,
    hourly_rate_max_cents: null,
    hourly_rate_note: null,
    reimbursement_principle: null,
    direct_payment_possible: null,
    allowed_household: null,
    allowed_cleaning: null,
    allowed_shopping: null,
    allowed_escort: null,
    allowed_leisure: null,
    allowed_snow_removal: null,
    allowed_lawn_mowing: null,
    insurance_note: null,
    tax_note: null,
    primary_official_url: null,
    secondary_official_url: null,
  },
  {
    state_code: 'SH',
    state_name: 'Schleswig-Holstein',
    is_available: false,
    research_status: 'pending_research',
    last_checked: null,
    training_required: false,
    training_hours: null,
    min_age: 16,
    max_hourly_rate_cents: null,
    max_concurrent_clients: null,
    relationship_exclusion_degree: 2,
    same_household_excluded: true,
    registration_authority: null,
    official_form_url: null,
    notes: 'Regeln noch nicht geprueft — Daten folgen',
    recognition_type: null,
    formal_pre_registration: null,
    hourly_rate_min_cents: null,
    hourly_rate_max_cents: null,
    hourly_rate_note: null,
    reimbursement_principle: null,
    direct_payment_possible: null,
    allowed_household: null,
    allowed_cleaning: null,
    allowed_shopping: null,
    allowed_escort: null,
    allowed_leisure: null,
    allowed_snow_removal: null,
    allowed_lawn_mowing: null,
    insurance_note: null,
    tax_note: null,
    primary_official_url: null,
    secondary_official_url: null,
  },
  {
    state_code: 'TH',
    state_name: 'Thueringen',
    is_available: false,
    research_status: 'pending_research',
    last_checked: null,
    training_required: false,
    training_hours: null,
    min_age: 16,
    max_hourly_rate_cents: null,
    max_concurrent_clients: null,
    relationship_exclusion_degree: 2,
    same_household_excluded: true,
    registration_authority: null,
    official_form_url: null,
    notes: 'Regeln noch nicht geprueft — Daten folgen',
    recognition_type: null,
    formal_pre_registration: null,
    hourly_rate_min_cents: null,
    hourly_rate_max_cents: null,
    hourly_rate_note: null,
    reimbursement_principle: null,
    direct_payment_possible: null,
    allowed_household: null,
    allowed_cleaning: null,
    allowed_shopping: null,
    allowed_escort: null,
    allowed_leisure: null,
    allowed_snow_removal: null,
    allowed_lawn_mowing: null,
    insurance_note: null,
    tax_note: null,
    primary_official_url: null,
    secondary_official_url: null,
  },
];

/** Nur verfuegbare Bundeslaender (is_available === true) */
export function getAvailableStates(): FederalStateRule[] {
  return FEDERAL_STATE_RULES.filter((s) => s.is_available);
}

/** Alle Bundeslaender inkl. nicht-verfuegbare */
export function getAllStates(): FederalStateRule[] {
  return [...FEDERAL_STATE_RULES];
}

/** Nur geprueft Bundeslaender (checked_official_sources) */
export function getVerifiedStates(): FederalStateRule[] {
  return FEDERAL_STATE_RULES.filter((s) => s.research_status === 'checked_official_sources');
}

/** Regeln fuer ein bestimmtes Bundesland (oder null) */
export function getStateRules(stateCode: string): FederalStateRule | null {
  return FEDERAL_STATE_RULES.find((s) => s.state_code === stateCode) ?? null;
}

/** Prueft ob ein Bundesland verfuegbar ist */
export function isStateAvailable(stateCode: string): boolean {
  const state = getStateRules(stateCode);
  return state?.is_available ?? false;
}

/**
 * Prueft ob eine Person das Mindestalter fuer ein Bundesland erfuellt.
 * Exakte Berechnung anhand Jahr/Monat/Tag.
 */
export function validateHelperAge(
  stateCode: string,
  dateOfBirth: Date,
  referenceDate: Date = new Date(),
): boolean {
  const state = getStateRules(stateCode);
  if (!state) return false;

  // Exakte Altersberechnung: Jahr-Differenz, ggf. -1 wenn Geburtstag noch nicht war
  let age = referenceDate.getFullYear() - dateOfBirth.getFullYear();
  const monthDiff = referenceDate.getMonth() - dateOfBirth.getMonth();
  if (
    monthDiff < 0 ||
    (monthDiff === 0 && referenceDate.getDate() < dateOfBirth.getDate())
  ) {
    age--;
  }

  return age >= state.min_age;
}

/**
 * Prueft ob ein Stundensatz innerhalb des Bundesland-Limits liegt.
 * Gibt true zurueck wenn kein Limit existiert (null = unbegrenzt).
 */
export function validateHourlyRate(
  stateCode: string,
  rateCents: number,
): boolean {
  const state = getStateRules(stateCode);
  if (!state) return false;

  // Kein Limit = jeder Betrag erlaubt
  if (state.max_hourly_rate_cents === null) return true;

  return rateCents <= state.max_hourly_rate_cents;
}

/** Maximale gleichzeitige Klienten fuer ein Bundesland (oder null = unbegrenzt) */
export function getMaxClients(stateCode: string): number | null {
  const state = getStateRules(stateCode);
  return state?.max_concurrent_clients ?? null;
}
